spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://eda.c94qcmycemn0.us-east-1.rds.amazonaws.com:3306/inventory
    username: #username
    password: #password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    aws:
      region:
        static: us-east-1
      stack:
        auto: false
      credentials:
        access-key: #ACCESS_KEY
        secret-key: #SECRET_KEY
      sqs:
        queue:
          inventory-queue: https://sqs.us-east-1.amazonaws.com/975049919121/inventory-queue

server:
  port: 8082

logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %logger{0} : %msg%n"
